# Generated by Django 3.0.8 on 2021-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='a',
        ),
        migrations.RemoveField(
            model_name='question',
            name='person',
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer10',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer11',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer12',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer5',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer6',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer7',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer8',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='answer9',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.IntegerField(default='', editable=False),
        ),
        migrations.AlterField(
            model_name='question',
            name='q',
            field=models.CharField(default='', editable=False, max_length=100),
        ),
    ]
