# Generated by Django 3.0.8 on 2021-02-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210214_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer10',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer11',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer12',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer2',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer3',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer4',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer5',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer6',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer7',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer8',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer9',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='q',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.IntegerField(),
        ),
    ]
