# Generated by Django 3.0.8 on 2021-02-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210214_0453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='qtype',
            field=models.IntegerField(default='0'),
        ),
    ]
